### ISSUE TITLE
Sync, Replacing Content

### ISSUE THREAD

**Issue by dtrikam1** [contentful/contentful-persistence.swift#12]
I am using Swift 3 with contentful-persistance and am having an issue with updating content, so for example if i add new content it replaces the existing content. I have noticed that deleting the content from core data and then calling ```self.sync.sync``` works fine. 

Any idea when the Contentful PersistanceTests will be updated?
``` Swift
it("can continue syncing from an existing data store") {
     // TODO: implement test
} 
``` 

Thank you for your help.

**Comment by loudmouth** [comment]
Hey @dtrikam1, apologies for the delayed response. I've been very busy to start the week off/

I'm not sure I fully understand the issue. When you say "replacing the existing content", what exactly is the issue? The delivery API is read-only, so the must recent state of your content is what is delivery, and this state should overwrite whatever you have locally.

Would you be willing to share some code to help further diagnose the issue? If so, it would be great if you could provide expected behavior vs. observed behavior.

Regarding the test, I will do my best to attend to this in the coming weeks. I'm currently working on publishing the first major version of the [contentful.swift CDA SDK] (it will be v1.0.0)(https://github.com/contentful/contentful.swift) and I will of course be attending to this persistence library as well to make sure they play nice together. At that time, I'll make sure test coverage is exhaustive and there are no TODO's left in the testing suite.

In the meantime, I'd consider this repo to be in beta—the objective-c counterpart is much more mature, battle tested, and has better test coverage. It may be worth evaluating on your end.

**Comment by loudmouth** [comment]
Hi @dtrikam1 , is there any chance you're willing to elaborate on your statement "if i add new content it replaces the existing content"? Did my last comment clarify things for you in any way?

**Comment by loudmouth** [comment]
Closing for now due to lack of response.
