### ISSUE TITLE
Contributing is too difficult

### ISSUE THREAD

**Issue by sebastianludwig** [contentful/contentful-persistence.swift#19]
I just opened an issue, do have a fix and wanted to implement it to open a PR. When I got to work, I hit a few obstacles:

- I get a compiler error for `import Contentful`, so I can't build the project.
- There's no scheme for the unit test target, so I can't run them.
- `make setup` fails with `[!] No 'Podfile' found in the project directory. make: *** [setup] Error 1`

I'm unsure how to proceed now.

**Comment by loudmouth** [comment]
Hey @sebastianludwig thanks so much. I'm really excited that you're interested in contributing. To be honest, this project was poorly labelled when I stepped into the role as the new maintainer. The bulk of my work the past few months has been on attending to issues in [contentful.objc](https://github.com/contentful/contentful.objc) and [contentful.swift](https://github.com/contentful/contentful.swift). However, it maybe be lucky coincidence that my priorities align with working on this persistence library. 

Regarding your current situation: the README needs to be updated. The project's dependencies are now being managed with carthage as it is not possible to manage internal dependencies with cocoapods and support carthage installation because of the added build phases that cocoapods requires, but it is possible to support pod installation while managing internal dependencies with carthage.

Installing carthage with `brew install carthage` and then running `carthage bootstrap` should get you up and running. I'll make sure to update the README as soon as I can.

**Comment by loudmouth** [comment]
@sebastianludwig [0.4.0](https://github.com/contentful/contentful-persistence.swift/releases/tag/0.4.0) was just pushed.

Let me know if you find contributing to be sufficiently easy now. As a heads up, I will be on vacation from June 24-July 9 and will therefore not be responding to new GH issues in a timely fashion until after my return.

**Comment by sebastianludwig** [comment]
Timely fashion? I hope not at all! Happy vacation 🌴 😉 

I'll take a look as soon as I find the time 👍

**Comment by loudmouth** [comment]
Hi @sebastianludwig , it is of my opinion that contributing is much easier now. I'm going to close this issue for now, but if you disagree with my opinion, please just re-open and let me know what you think of the current workflow when you have time.
