### ISSUE TITLE
Xcode 9 Asset object could not be created

### ISSUE THREAD

**Issue by tapwork** [contentful/contentful-persistence.swift#29]
Can't start our app with Xcode 9. The ContentfulPersistence's SynchronizationManager can't find the Type `Asset`.
It will be loaded as standard `NSManagedObject`
Therefore the `SynchronizationManager` will leave at line 142
<img width="734" alt="screen shot 2017-08-23 at 12 39 53" src="https://user-images.githubusercontent.com/397342/29612187-a8947036-8800-11e7-9167-8e0bb42571da.png">

Core Data is saying: "CoreData: warning: Unable to load class named 'Asset' for entity 'Asset'.  Class not found, using default NSManagedObject instead." 

I am using NSManagedObject subclasses created with mogenerator

**Comment by loudmouth** [comment]
Hey @tapwork, I haven't tried contentful-persistence.swift on Xcode9 yet. I'll have some time tomorrow morning to look into this.

**Comment by loudmouth** [comment]
Hey @tapwork , I'm not yet sure that this is an issue with the library itself.

I just ran the tests on Xcode 9 and everything works fine.

In this case, is your `AssetPersistable` object is called `Asset`? Have you checked if your class names are configured correctly in your .xcdatamodel file? You have either two options:

1. You can either add `@objc(Asset)` above your class definition, and then in your .xcdatamodel > Configurations, set the class name to simply Asset. See the attached screenshot.
![screen shot 2017-08-24 at 12 07 36](https://user-images.githubusercontent.com/4554909/29661606-d86949e8-88c4-11e7-9383-3cb8831fe71e.png)

2. Alternatively, you can omit the `@objc` attribute, but then add the module namespace in your configuration: `MyAppName.Asset` so that it correctly finds your swift NSManagedObject subclass.

If I'm totally off here and this has nothing to do with your issue, maybe you would be able to share what the `Error` instance actually says here. As it should be printable.

**Comment by tapwork** [comment]
@loudmouth thanks. it works now when I specify the module by `Current Product Module`.
I removed the objc . it is not needed, which is nicer.

**Comment by loudmouth** [comment]
Glad everything worked out :-)
