### ISSUE TITLE
Can't use the same asset for more than one Entry

### ISSUE THREAD

**Issue by tapwork** [contentful/contentful-persistence.swift#44]
I wasn't sure if this issue belongs to this repo or the standard Contentful.swift repo.
The issue is as follows:
I have two `Entry` items in Contentful and both have a relationship to the same `Asset` (image) in contentful.
This works fine in the Contentful admin web frontend. Also our Android app shows for both entries the same image.
But the iOS app with CoreData does not show the image for both entries. Only the last entry will show the image. 
The first entry has ```image = nil```.
This behavior seems to be expected (not nice) since the `Entry` model has a one-to-one relationship to the `Asset` in `CoreData` and is mapped via the `id` (same)  . What is the best practise to avoid this?

**Comment by loudmouth** [comment]
Hi @tapwork 

If the issue is regarding CoreData, then I think this is the correct repo.


I have just added [tests in a new branch](https://github.com/contentful/contentful-persistence.swift/commit/acfe929bc6f6ccb8251406853dffd808fd75875d) testing that multiple entries can link to the same asset and everything works just fine.

The expected behavior is that multiple entries can point to the same asset, so I'm not quite sure what is causing the problem on your end. Your entry model should have a one-to-one relationship configured if you only expect a single asset from the API. You can see in the screenshot attached how a link field linking to many assets differs from a link field linking to a single asset in the content model editor for Contentful. 

<img width="557" alt="screen shot 2017-12-20 at 11 37 49" src="https://user-images.githubusercontent.com/4554909/34225162-3d1aa514-e57a-11e7-8ba2-ddd3d2045535.png">

The expected behavior of the persistence library is that _all_ links should always be resolved if they exist in your Contentful space.

**Comment by tapwork** [comment]
Hi @loudmouth 

I fixed it. The issue was that we have a one - to - one relation for both sides.
Also a 1-1 for the inverse relation ship from the `Asset` to the `Entry`
I made the inverse relation from the `Asset` to the `Entry` 1 - to - many.  So one asset can have multiple entries. that fixed it. Enjoy your holidays.
