### ISSUE TITLE
Resolve all relationships after seeding data from all JSON files

### ISSUE THREAD

**Issue by marcin-bo** [contentful/contentful-persistence.swift#47]
Hello,

I found an issue in the library in resolving relationships between entities. I'm using [contentful-utilities](https://github.com/contentful/contentful-utilities.swift) to generate JSON files with data. 

The output of `contentful-utilities` is:
```
0.json
1.json
2.json
```

I seed those files at first launch of the app. I have two entities in one-to-many relationship.
Parent entity is defined in `0.json` file.
One of child entities is defined in `1.json`. And after seeding database there is no conection between them.

The problem is that the library resolves relationships after seeding each file. That's why there is no relationship between entites from different JSON files. It should be done after data from all files is seeded and only once. See my quick fix:

```
// 
// file: SynchronizationManager.swift
// 

public func update(with syncSpace: SyncSpace) {
      // ...

      self?.update(syncToken: syncSpace.syncToken)
      // self?.resolveRelationships() -> remove this line
      self?.save()

      // ...
}

// define new function that handles resolving relationships
public func lateResolveRelationships() {
      persistentStore.performAndWait { [weak self] in
            self?.resolveRelationships()
            self?.save()
      }
}
```

```
//
// file: SynchronizationManager+SeedDB.swift
//

// ...
public func seedDBFromJSONFiles(in directory: String, in bundle: Bundle) throws {
      // ...
      self.lateResolveRelationships() // in last line call new function after data from all JSONs is seeded
}
```

**Comment by marcin-bo** [comment]
Actually we should not delete `self?.resolveRelationships()` in `SynchronizationManager.update()` to keep client's synchronization working:

```
// 
// file: SynchronizationManager.swift
// 

// define new function that handles resolving relationships
public func lateResolveRelationships() {
      persistentStore.performAndWait { [weak self] in
            self?.resolveRelationships()
            self?.save()
      }
}
```

```
//
// file: SynchronizationManager+SeedDB.swift
//

// ...
public func seedDBFromJSONFiles(in directory: String, in bundle: Bundle) throws {
      // ...
      self.lateResolveRelationships() // in last line call new function after data from all JSONs is seeded
}
```

**Comment by loudmouth** [comment]
Hey @marcin-bo thanks for the report.

It sounds like there are two separate issues here:

#### Issue 1: Bug with link resolution for multiple page syncs.

I'm surprised to hear this isn't working as [I have tests](https://github.com/contentful/contentful-persistence.swift/blob/master/Tests/ContentfulPersistenceTests/ComplexSyncTests.swift#L201). These tests use the following two stubs which are the separate pages: [1](https://github.com/contentful/contentful-persistence.swift/blob/master/Tests/ContentfulPersistenceTests/ComplexTestStubs/multi-page-link-resolution1.json) and [2](https://github.com/contentful/contentful-persistence.swift/blob/master/Tests/ContentfulPersistenceTests/ComplexTestStubs/multi-page-link-resolution2.json) for resolving relationships that have parents in one page and children in another—regardless of which is on which page. 

Each new `SyncSpace` that is sent to this persistence lib from the core SDK contains the latest delta changes which come on each page. The persistence lib then iterates over _all_ entries (new and old) and resolves links to all other entries and assets... At least this is how this library is supposed to work. If your convinced there is a bug here, maybe you could help me and open a support request at [support.contentful.com](https://support.contentful.com) and tell the support folks that the iOS SDK dev sent you there and link this Github issue. The reason i suggest opening a ticket is that your specific content and content model may highlight an edge case that is being overlooked.

#### Issue 2: Non-optimized link resolution when seeding from database.

The abovementioned implementation was meant to handle all cases when hitting the API, but when seeding from bundled content, I think you're right that it makes sense to resolve the relationships after all pages have been deserialized rather than between each page.

Anyway, I I won't be able to get to this until Monday at least.

**Comment by marcin-bo** [comment]
Hi @loudmouth 

I think that in my case it's issue 2. When I sync database with Contentful API relationships are resolved correctly. When I seed database some relatioships are missing.

**Comment by loudmouth** [comment]
Hey @marcin-bo sorry I hadn't gotten to this yet. I had quite a bit of work to go through yesterday an today. Rest assured I'll address it this week. In the meantime, use your fork if that's working for you ;-)

**Comment by loudmouth** [comment]
@marcin-bo I found the real culprit here: `SyncSpace` has a [method](https://github.com/contentful/contentful.swift/blob/master/Sources/Contentful/SyncSpace.swift#L155) `updateWithDiffs(from syncSpace: SyncSpace` that needs to be called to merge instances in memory before they are sent to this library to have their data persisted.

I will need to merge a PR on the main contentful.swift repo to make that method `public` and then replace the `self.update(with: syncSpace) call in this lib with the folling:

```
let newestSyncSpace = try jsonDecoder.decode(SyncSpace.self, from: data)
syncSpace.updateWithDiffs(from: newestSyncSpace)
``` 

With that change, relationship resolution only needs to happen once, after all the files have been loaded in memory, i.e. outside of the `while` loop. This will also make the behavior consistent with doing api requests during runtime and then persisting the data to disk with this lib.

Stay tuned for a fix.

**Comment by loudmouth** [comment]
Actually, rather than merging all sync spaces in memory (who knows what kind of memory ballooning a large space could cause), i have found a way to manually keep track of the relationship metadata that the persistence lib uses to resolve relationships. The `relationshipsToResolve` property now keeps track of which relationships have already been resolved.

**Comment by loudmouth** [comment]
@marcin-bo [`0.9.1`](https://github.com/contentful/contentful-persistence.swift/releases/tag/0.9.1) is now available on Cocoapods and via Carthage or SPM.
