### ISSUE TITLE
Localised assets do not contain URL when they fallback to default value

### ISSUE THREAD

**Issue by tadasz** [contentful/contentful-persistence.swift#62]
- contentful-persistence version number: 0.12.0
- Xcode version number: 9.4.1
- Target operating system(s) and version number(s)
  - [x] iOS: iOS 10
  - [ ] tvOS: 
  - [ ] watchOS:
  - [ ] macOS:
- Package manager:
  - [ ] Carthage
  - [x] Cocoapods

When syncing assets, URL for localized assets do not fall-back to default localization, it's showed as nil.

All assets can be localized but it's a very rare case that you need different images for different languages. So I would expect that it's enough to have one version of the image and when the asset is synced default URL is saved for all locales. This is not a case now. You need to add images for all languages if you want to have a URL for different locales. If you don't add different versions, the asset is created but URL is nil. 

Please let me know if this is a bug or expected behavior.

**Comment by loudmouth** [comment]
Hey @tadasz 

Sounds like a bug, but I will need to do some investigating later today to confirm.

cheers

**Comment by loudmouth** [comment]
There is indeed a bug—actually the issue is in the main package, [contentful.swift](https://github.com/contentful/contentful.swift), the issue being that the [accessor for `urlString` on `Asset`](https://github.com/contentful/contentful.swift/blob/master/Sources/Contentful/Asset.swift#L61-L63) doesn't attempt to get the localizable value and rather just takes the the default.

I do not have time this week to fix this, but hope I can get to it next week. Apologies for any delay.

**Comment by tadasz** [comment]
Let me know when you have any news about it ;)

**Comment by loudmouth** [comment]
Sorry, have been very busy. Fix will come by the end of the week!

**Comment by loudmouth** [comment]
Hi @tadasz I'm sorry it took so long to get to this. I just put up a PR for the main SDK: 

https://github.com/contentful/contentful.swift/pull/215

I will need to have it reviewed, then a sister PR will happen here.

**Comment by loudmouth** [comment]
@tadasz [0.12.1](https://github.com/contentful/contentful-persistence.swift/releases/tag/0.12.1) was just released!

Don't hesitate to re-open this issue if the problem persists

**Comment by tadasz** [comment]
thanks, will le you know

**Comment by tadasz** [comment]
New issues :(

Not really sure what is causing them, but the problem is this:
We synchronize the database with 1 language. Then on the next run, we add an additional language. This causes that URL for assets in nil.

Let me know if I can provide more info.

Thanks

**Comment by loudmouth** [comment]
Hi @tadasz apologies for the delayed response; I had been on vacation until yesterday.

When you say "we add an additional language" do you mean that you simply added a new locale to your space? Or do you mean that you actually input content for an additional locale on an actual asset? 

With this persistence lib, you should get multiple instances of your asset, one for each locale. Is the URL `nil` for all instances?

**Comment by tadasz** [comment]
We added additional language to our space. We did enter translations for text but haven't changed any assets.

If we delete old data and sync on a fresh clean database then everything is ok, but if there is old data then assets for new language somehow are nil.

**Comment by loudmouth** [comment]
Hi @tadasz I have done some testing on my end and confirmed with the API team that this is a limitation of the API:

It turns out that that adding a new locale to a space will not cause subsequent `sync` calls to return "new" content for assets ("new" in this case refering to populating the asset for all locales on the space with fallback-locale logic reflected).

I think the best strategy would be either to do another initial sync; or you could write a script to update your assets in some manner.

**Comment by tadasz** [comment]
is this something you are planning to fix at some point or we should think of some workaround?

**Comment by loudmouth** [comment]
Hi @tadasz as far as I know, this issue will not be attended to on the API level, so I would suggest exploring workarounds such as the two I suggested above:

> I think the best strategy would be either to do another initial sync; or you could write a script to update your assets in some manner.
