### ISSUE TITLE
Management of properties and relationships

### ISSUE THREAD

**Issue by wainglaister** [contentful/contentful-persistence.swift#73]
It seems that the assumptions made around the processing of properties and relationships is problematic when the local data store includes fields which aren't in the remote model. (hopefully I'm missing something, but there's nothing I can see in the docs)

This is initially because relationships are calculated to be anything that isn't found to be a property, so to prevent invalid relationship handling you're lead to add dummy mappings to `fieldMapping()` for anything which is local but not remote (including transients). This however is later a problem because the field mapping from remote to local just processes everything defined in `fieldMapping()` and thus sets any local-only fields to nil.

At minimum the field mapping should check that the field name exists in the data coming from the server and ignore any core data content which doesn't exist in the download - but this is how empty field deletion is managed so that's actually hard...

Example scenarios are things like:

1. A remote value needs to be converted before being stored into the model (this could be worked around by using a transient and converting on 'get' but this could be difficult for historic reasons and efficiency depending on the conversion required)
2. The server contains general resources and a local record needs to be kept of what's been seen or something like that
3. You want to convert the supplied strings to date objects once

Related to this, that concept of mapping is a big thing. The `fieldMapping()` could include an optional closure to run as a way to simply add support for it...

**Comment by loudmouth** [comment]
Hi @wainglaister thanks for the well thought through issue description.

To make sure I understand your use-case, you are trying to store properties on your model instances which are being pulled from elsewhere (i.e. are not stored in Contentful). Because of the way the library infers which properties are regular fields, and which are relationships, coupled with the fact that  the library, correctly, infers which fields/relationships should be nullified by looking at omitted JSON properties, you are now unable to store extra data on your model. Is that all correct?

This is the first time the use-case of additional data on these models has been brought up for Contentful+Swift. Am I correct in that you might have an idea on how to address this issue? PRs are very welcome.

One alternative I have considered heavily and that is now enabled by the main contentful.swift library is now capable of is subclassing `Realm.Object` or `NSManagedObject` while conforming to `EntryDecodable`. This would obviate the need for the contentful-persistence.swift library and enable users to leverage regular queries, rather than syncing the entire backend to device as this library does.

**Comment by wainglaister** [comment]
Basically, yes, that's the situation.

I had a couple of ideas about potential changes, but I have a concern that the changes required would be quite extensive so instead I've worked around this issue with a combination of fake mappings (to avoid relationship processing) and an override of `setValue:forKey:` to prevent, what in my situation are mandatory or local fields, inadvertent nilling.

Being able to use queries and, effectively, having an ignore list for properties would be nice...

**Comment by loudmouth** [comment]
I also haven't addressed this as I also believe the changes would be quite extensive and current capacity limitations mean that we don't have the time to address a big feature change like this at the moment.

I have done some protoyping and the plain contentful.swift SDK _can_ indeed be used with regular queries and CoreData or Realm. With the CoreData variation, you would conform to `EntryDecodable` (which is an extension of `Decodable`) and you would do something similar to what is described[ in this article](https://medium.com/@andrea.prearo/working-with-codable-and-core-data-83983e77198e); basically attaching your `NSManagedObjectContext` to the `client.jsonDecoder` via it's `userInfo` dictionary.

With Realm, things are even easier, since you don't have to use a visual model editor as you do with CoreData, and nothing special needs to be done for decoding. 

Here is some example code of a Swift file that uses realm and Contentful in tandem, there is no real space id or accesstoken in there, but you should be able to infer the model based on the model class declarations. Also note how saving to realm and multi-threading is handled:

```
import UIKit
import Contentful
import RealmSwift

@objcMembers
final class Person: Object, EntryDecodable, FieldKeysQueryable {

    static let contentTypeId = "person"

    dynamic var name: String = ""
    dynamic var shortBio: String = ""

    dynamic var id: String = ""
    dynamic var updatedAt: Date? = nil
    dynamic var createdAt: Date? = nil
    dynamic var localeCode: String? = ""

    convenience init(from decoder: Decoder) throws {
        self.init()
        let sys     = try decoder.sys()
        id          = sys.id
        updatedAt   = sys.updatedAt
        createdAt   = sys.createdAt
        localeCode  = sys.locale

        let fields  = try decoder.contentfulFieldsContainer(keyedBy: FieldKeys.self)
        name        = try fields.decode(String.self, forKey: .name)
        shortBio    = try fields.decode(String.self, forKey: .shortBio)
    }
    override static func primaryKey() -> String? {
        return "id"
    }
    enum FieldKeys: String, CodingKey {
        case name, shortBio
    }
}
@objcMembers
final class BlogPost: Object, EntryDecodable, FieldKeysQueryable {
    
    static let contentTypeId = "blogPost"

    dynamic var title: String = ""
    dynamic var slug: String = ""
    dynamic var author: Person? = nil

    dynamic var id: String = ""
    dynamic var updatedAt: Date? = nil
    dynamic var createdAt: Date? = nil
    dynamic var localeCode: String? = ""

    convenience init(from decoder: Decoder) throws {
        self.init()
        let sys     = try decoder.sys()
        id          = sys.id
        updatedAt   = sys.updatedAt
        createdAt   = sys.createdAt
        localeCode  = sys.locale

        let fields  = try decoder.contentfulFieldsContainer(keyedBy: FieldKeys.self)
        title       = try fields.decode(String.self, forKey: .title)
        slug        = try fields.decode(String.self, forKey: .slug)

        try fields.resolveLink(forKey: .author, decoder: decoder) { [weak self] author in
            self?.author = author as? Person
        }
    }
    override static func primaryKey() -> String? {
        return "id"
    }
    enum FieldKeys: String, CodingKey {
        case title, slug, author
    }
}
class ViewController: UIViewController {

    let client: Client

    let realm: Realm

    init() {
        client = Client(spaceId: "<space_id>",
                        accessToken: "<access_token>",
                        contentTypeClasses: [BlogPost.self, Person.self])
        realm = try! Realm(configuration: .defaultConfiguration)
        super.init(nibName: nil, bundle: nil)
    }

    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = .blue

        client.fetchArray(of: BlogPost.self, matching: .order(by: try! Ordering(sys: .updatedAt))) { result in
            switch result {
            case .success(let response):
                let posts = response.items

                let newRealm = try! Realm(configuration: .defaultConfiguration)
                try! newRealm.write {
                    newRealm.add(posts, update: true)
                }
                self.realmify()

            case .error:
                print("oh no")
            }
        }
    }

    func realmify() {
        DispatchQueue.main.async {
            let persons = self.realm.objects(Person.self)
            print(persons)
        }
    }
}
```
