### ISSUE TITLE
Force re-sync all the data possible?

### ISSUE THREAD

**Issue by pravking** [contentful/contentful-persistence.swift#93]

**Comment by tomkowz** [comment]
Hello @pravking,

You can re-sync content of the core data by setting sync token to nil and then performing a sync request.

```
    /// Resets the sync token and allow for further sync of the content again. Make sure you cleaned up all your
    /// models before resyncing.
    func resetSyncToken(moc: NSManagedObjectContext) {
        let fetchRequest = NSFetchRequest<NSFetchRequestResult>(entityName: String(describing: SyncSpace.self))

        do {
            guard let syncSpace = try moc.fetch(fetchRequest).first as? SyncSpace else { return }
            syncSpace.syncToken = nil

        } catch let error as NSError {
            print(error)
        }
    }
```

**Comment by pravking** [comment]
Thanks for the solution @tomkowz.

Had to use 'SyncInfo' instead of 'SyncSpace' given in the code snippet to get it working.

**Comment by tomkowz** [comment]
Hmm... Okay, I see the `SyncInfo` does not expose the `syncToken`. I think you could then remove the `SyncInfo` from the store and then re-sync. Removing it from the store will have the same effect like setting it to nil.

```
    private func deleteSyncInfo() {
        let fetchRequest: NSFetchRequest<NSFetchRequestResult> = NSFetchRequest(entityName: "SyncInfo")
        let deleteRequest = NSBatchDeleteRequest(fetchRequest: fetchRequest)

        do {
            try managedObjectContext.persistentStoreCoordinator?.execute(deleteRequest, with: managedObjectContext)
            try managedObjectContext.save()

        } catch let error as NSError {
            print(error)
        }
    }
```

Btw. I know ContentfulPersistence just for a bit now but in my demo projects for debugging purposes I am using a custom `SyncSpace` instead of `SyncInfo` because of the easy access to the token.

When you switch to use `SyncSpace` you'll not need to do a delete request because token will be nil anyway.

Let me know if the above work for you.

**Comment by pravking** [comment]
Thanks @tomkowz removing SyncInfo from store is also working.

Also, is it necessary to clear all the models before re-syncing? 
When I tried clearing only the SyncInfo model and then calling sync also the re-syncing is working.

**Comment by tomkowz** [comment]
I don't think this is necessary. If that works for you without removing data then that's fine. That was my advice just to make sure. I think we can close this one then.
